/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { Component, OnInit, OnDestroy, ChangeDetectionStrategy } from '@angular/core';
import { SpillService } from './spill.service';
import { LoadLocalesSpillText } from './spill.locales';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-spill',
  templateUrl: './spill.component.html',
  styleUrls: ['./spill.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class SpillComponent implements OnInit, OnDestroy {
  sub: Subscription;

  constructor(public spillService: SpillService, public router: Router) { }

  GetSpill() {
    this.sub = this.spillService.GetSpill(this.router).subscribe();
  }

  ngOnInit(): void {
    LoadLocalesSpillText(this.spillService);
  }

  ngOnDestroy() {
    this.sub.unsubscribe();
  }

}
