/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { VPScenarioRoutingModule } from './vpscenario-routing.module';
import { MaterialModule } from '../../app-material.module';
import { VPScenarioComponent } from './vpscenario.component';

@NgModule({
  declarations: [ VPScenarioComponent ],
  imports: [
    CommonModule,
    RouterModule,
    VPScenarioRoutingModule,
    MaterialModule
  ]
})
export class VPScenarioModule { }
