/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { Component, OnInit, OnDestroy, ChangeDetectionStrategy } from '@angular/core';
import { VPScenarioIDAndRawResultsService } from './vpscenarioidandrawresults.service';
import { LoadLocalesVPScenarioIDAndRawResultsText } from './vpscenarioidandrawresults.locales';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-vpscenarioidandrawresults',
  templateUrl: './vpscenarioidandrawresults.component.html',
  styleUrls: ['./vpscenarioidandrawresults.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class VPScenarioIDAndRawResultsComponent implements OnInit, OnDestroy {
  sub: Subscription;

  constructor(public vpscenarioidandrawresultsService: VPScenarioIDAndRawResultsService, public router: Router) { }

  GetVPScenarioIDAndRawResults() {
    this.sub = this.vpscenarioidandrawresultsService.GetVPScenarioIDAndRawResults(this.router).subscribe();
  }

  ngOnInit(): void {
    LoadLocalesVPScenarioIDAndRawResultsText(this.vpscenarioidandrawresultsService);
  }

  ngOnDestroy() {
    this.sub.unsubscribe();
  }

}
