/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { TestBed } from '@angular/core/testing';

import { TVItemTVAuthService } from './tvitemtvauth.service';

describe('TVItemTVAuthService', () => {
  let service: TVItemTVAuthService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(TVItemTVAuthService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
