/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { TVItemTVAuthTextModel }
from './tvitemtvauth.models';
import { TVItemTVAuthService }
from './tvitemtvauth.service';

export function LoadLocalesTVItemTVAuthText(tvitemtvauthService: TVItemTVAuthService) {
    let tvitemtvauthTextModel: TVItemTVAuthTextModel = {
        Title: 'The title',
}

    if ($localize.locale === 'fr-CA') {
        tvitemtvauthTextModel.Title = 'Le Titre';
    }

    tvitemtvauthService.UpdateTVItemTVAuthText(tvitemtvauthTextModel);
}
