/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { RegisterTextModel }
from './register.models';
import { RegisterService }
from './register.service';

export function LoadLocalesRegisterText(registerService: RegisterService) {
    let registerTextModel: RegisterTextModel = {
        Title: 'The title',
}

    if ($localize.locale === 'fr-CA') {
        registerTextModel.Title = 'Le Titre';
    }

    registerService.UpdateRegisterText(registerTextModel);
}
