/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { RegisterRoutingModule } from './register-routing.module';
import { MaterialModule } from '../../app-material.module';
import { RegisterComponent } from './register.component';

@NgModule({
  declarations: [ RegisterComponent ],
  imports: [
    CommonModule,
    RouterModule,
    RegisterRoutingModule,
    MaterialModule
  ]
})
export class RegisterModule { }
