/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { InfrastructureRoutingModule } from './infrastructure-routing.module';
import { MaterialModule } from '../../app-material.module';
import { InfrastructureComponent } from './infrastructure.component';

@NgModule({
  declarations: [ InfrastructureComponent ],
  imports: [
    CommonModule,
    RouterModule,
    InfrastructureRoutingModule,
    MaterialModule
  ]
})
export class InfrastructureModule { }
