/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { TestBed } from '@angular/core/testing';

import { RTBStringPosService } from './rtbstringpos.service';

describe('RTBStringPosService', () => {
  let service: RTBStringPosService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(RTBStringPosService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
