/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { CalDecayComponent } from './caldecay.component';

describe('CalDecayComponent', () => {
  let component: CalDecayComponent;
  let fixture: ComponentFixture<CalDecayComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ CalDecayComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(CalDecayComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
