/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { HttpRequestModel } from '../../models/http.model';
import { SubsectorMWQMSampleYear } from 'src/app/models/generated/SubsectorMWQMSampleYear.model';

export interface SubsectorMWQMSampleYearTextModel {
    Title?: string
}

export interface SubsectorMWQMSampleYearModel extends HttpRequestModel {
    SubsectorMWQMSampleYearList: SubsectorMWQMSampleYear[];
}
