/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { HttpRequestModel } from '../../models/http.model';
import { MapInfoPoint } from 'src/app/models/generated/MapInfoPoint.model';

export interface MapInfoPointTextModel {
    Title?: string
}

export interface MapInfoPointModel extends HttpRequestModel {
    MapInfoPointList: MapInfoPoint[];
}
