/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [[ModelClassName]TestGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 
using System;
using System.Text;
using Xunit;
using System.Linq;
using System.Globalization;
using System.Transactions;
using System.Collections.Generic;
using CSSPModels.Resources;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Reflection;
using CSSPEnums;
using System.ComponentModel.DataAnnotations;

namespace CSSPModels.Tests
{

    public partial class TVFileLanguageTest
    {
        #region Variables
        #endregion Variables

        #region Properties
        private TVFileLanguage tVFileLanguage { get; set; }
        #endregion Properties

        #region Constructors
        public TVFileLanguageTest()
        {
            tVFileLanguage = new TVFileLanguage();
        }
        #endregion Constructors

        #region Tests Functions public
        [Fact]
        public void TVFileLanguage_Properties_Test()
        {
            List<string> propNameList = new List<string>() { "TVFileLanguageID", "TVFileID", "Language", "FileDescription", "TranslationStatus", "LastUpdateDate_UTC", "LastUpdateContactTVItemID",  }.OrderBy(c => c).ToList();
            List<string> propNameNotMappedList = new List<string>() { "HasErrors",  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties().OrderBy(c => c.Name))
            {
                if (!propertyInfo.GetGetMethod().IsVirtual
                    && propertyInfo.Name != "ValidationResults"
                    && !propertyInfo.CustomAttributes.Where(c => c.AttributeType.Name.Contains("NotMappedAttribute")).Any())
                {
                    Assert.Equal(propNameList[index], propertyInfo.Name);
                    index += 1;
                }
            }

            Assert.Equal(propNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                foreach (CustomAttributeData customAttributeData in propertyInfo.CustomAttributes)
                {
                    if (customAttributeData.AttributeType.Name == "NotMappedAttribute")
                    {
                        Assert.Equal(propertyInfo.Name, propNameNotMappedList[index]);
                        index += 1;
                    }
                }
            }

            Assert.Equal(propNameNotMappedList.Count, index);

        }
        [Fact]
        public void TVFileLanguage_Navigation_Test()
        {
            List<string> foreignNameList = new List<string>() {  }.OrderBy(c => c).ToList();
            List<string> foreignNameCollectionList = new List<string>() {  }.OrderBy(c => c).ToList();

            int index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties())
            {
                if (propertyInfo.GetGetMethod().IsVirtual && !propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.True(foreignNameList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.Equal(foreignNameList.Count, index);

            index = 0;
            foreach (PropertyInfo propertyInfo in typeof(TVFileLanguage).GetProperties().Where(c => c.Name != "ValidationResults").OrderBy(c => c.Name).ToList())
            {
                if (propertyInfo.GetGetMethod().ReturnType.Name.StartsWith("ICollection"))
                {
                    Assert.True(foreignNameCollectionList.Contains(propertyInfo.Name));
                    index += 1;
                }
            }

            Assert.Equal(foreignNameCollectionList.Count, index);

        }
        [Fact]
        public void TVFileLanguage_Has_ValidationResults_Test()
        {
             Assert.True(typeof(TVFileLanguage).GetProperties().Where(c => c.Name == "ValidationResults").Any());
        }
        [Fact]
        public void TVFileLanguage_Every_Property_Has_Get_Set_Test()
        {
               int val1 = 45;
               tVFileLanguage.TVFileLanguageID = val1;
               Assert.Equal(val1, tVFileLanguage.TVFileLanguageID);
               int val2 = 45;
               tVFileLanguage.TVFileID = val2;
               Assert.Equal(val2, tVFileLanguage.TVFileID);
               LanguageEnum val3 = (LanguageEnum)3;
               tVFileLanguage.Language = val3;
               Assert.Equal(val3, tVFileLanguage.Language);
               string val4 = "Some text";
               tVFileLanguage.FileDescription = val4;
               Assert.Equal(val4, tVFileLanguage.FileDescription);
               TranslationStatusEnum val5 = (TranslationStatusEnum)3;
               tVFileLanguage.TranslationStatus = val5;
               Assert.Equal(val5, tVFileLanguage.TranslationStatus);
               DateTime val6 = new DateTime(2010, 3, 4);
               tVFileLanguage.LastUpdateDate_UTC = val6;
               Assert.Equal(val6, tVFileLanguage.LastUpdateDate_UTC);
               int val7 = 45;
               tVFileLanguage.LastUpdateContactTVItemID = val7;
               Assert.Equal(val7, tVFileLanguage.LastUpdateContactTVItemID);
               bool val8 = true;
               tVFileLanguage.HasErrors = val8;
               Assert.Equal(val8, tVFileLanguage.HasErrors);
               IEnumerable<ValidationResult> val27 = new List<ValidationResult>() { new ValidationResult("First CSSPError Message") }.AsEnumerable();
               tVFileLanguage.ValidationResults = val27;
               Assert.Equal(val27, tVFileLanguage.ValidationResults);
        }
        #endregion Tests Functions public
    }
}
