/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { Component, OnInit, OnDestroy, ChangeDetectionStrategy } from '@angular/core';
import { BoxModelCalNumbService } from './boxmodelcalnumb.service';
import { LoadLocalesBoxModelCalNumbText } from './boxmodelcalnumb.locales';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { BoxModelResultTypeEnum_GetIDText } from 'src/app/enums/generated/BoxModelResultTypeEnum';

@Component({
  selector: 'app-boxmodelcalnumb',
  templateUrl: './boxmodelcalnumb.component.html',
  styleUrls: ['./boxmodelcalnumb.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class BoxModelCalNumbComponent implements OnInit, OnDestroy {
  sub: Subscription;

  constructor(public boxmodelcalnumbService: BoxModelCalNumbService, public router: Router) { }

  GetBoxModelCalNumb() {
    this.sub = this.boxmodelcalnumbService.GetBoxModelCalNumb(this.router).subscribe();
  }

  GetBoxModelResultTypeEnumText(enumID: number) {
    return BoxModelResultTypeEnum_GetIDText(enumID)
  }

  ngOnInit(): void {
    LoadLocalesBoxModelCalNumbText(this.boxmodelcalnumbService);
  }

  ngOnDestroy() {
    this.sub.unsubscribe();
  }

}
