/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { TestBed } from '@angular/core/testing';

import { PolSourceInactiveReasonEnumTextAndIDService } from './polsourceinactivereasonenumtextandid.service';

describe('PolSourceInactiveReasonEnumTextAndIDService', () => {
  let service: PolSourceInactiveReasonEnumTextAndIDService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(PolSourceInactiveReasonEnumTextAndIDService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
});
