 /* Auto generated from the CSSPCodeWriter.proj by clicking on the [_ExtensionEnumCastingGenerated.cs] button
 *
 * Do not edit this file.
 *
 */ 

using CSSPEnums;
using CSSPModels;

namespace CSSPServices
{
    public static class ExtentionEnumCasting
    {
        public static object GetEnumCasting(WhereInfo whereInfo)
        {
            switch (whereInfo.EnumType.Name)
            {
               case "ActionDBTypeEnum":
                   return (ActionDBTypeEnum)whereInfo.ValueInt;
               case "AddContactTypeEnum":
                   return (AddContactTypeEnum)whereInfo.ValueInt;
               case "DatabaseTypeEnum":
                   return (DatabaseTypeEnum)whereInfo.ValueInt;
               case "EntityQueryTypeEnum":
                   return (EntityQueryTypeEnum)whereInfo.ValueInt;
               case "PolSourceObsInfoTypeEnum":
                   return (PolSourceObsInfoTypeEnum)whereInfo.ValueInt;
               case "AddressTypeEnum":
                   return (AddressTypeEnum)whereInfo.ValueInt;
               case "AerationTypeEnum":
                   return (AerationTypeEnum)whereInfo.ValueInt;
               case "AlarmSystemTypeEnum":
                   return (AlarmSystemTypeEnum)whereInfo.ValueInt;
               case "AnalysisCalculationTypeEnum":
                   return (AnalysisCalculationTypeEnum)whereInfo.ValueInt;
               case "AnalysisReportExportCommandEnum":
                   return (AnalysisReportExportCommandEnum)whereInfo.ValueInt;
               case "AnalyzeMethodEnum":
                   return (AnalyzeMethodEnum)whereInfo.ValueInt;
               case "AppTaskCommandEnum":
                   return (AppTaskCommandEnum)whereInfo.ValueInt;
               case "AppTaskStatusEnum":
                   return (AppTaskStatusEnum)whereInfo.ValueInt;
               case "BeaufortScaleEnum":
                   return (BeaufortScaleEnum)whereInfo.ValueInt;
               case "BoxModelResultTypeEnum":
                   return (BoxModelResultTypeEnum)whereInfo.ValueInt;
               case "ClassificationTypeEnum":
                   return (ClassificationTypeEnum)whereInfo.ValueInt;
               case "CollectionSystemTypeEnum":
                   return (CollectionSystemTypeEnum)whereInfo.ValueInt;
               case "ContactTitleEnum":
                   return (ContactTitleEnum)whereInfo.ValueInt;
               case "CSSPWQInputSheetTypeEnum":
                   return (CSSPWQInputSheetTypeEnum)whereInfo.ValueInt;
               case "CSSPWQInputTypeEnum":
                   return (CSSPWQInputTypeEnum)whereInfo.ValueInt;
               case "DailyOrHourlyDataEnum":
                   return (DailyOrHourlyDataEnum)whereInfo.ValueInt;
               case "DisinfectionTypeEnum":
                   return (DisinfectionTypeEnum)whereInfo.ValueInt;
               case "DrogueTypeEnum":
                   return (DrogueTypeEnum)whereInfo.ValueInt;
               case "EmailTypeEnum":
                   return (EmailTypeEnum)whereInfo.ValueInt;
               case "ExcelExportShowDataTypeEnum":
                   return (ExcelExportShowDataTypeEnum)whereInfo.ValueInt;
               case "FacilityTypeEnum":
                   return (FacilityTypeEnum)whereInfo.ValueInt;
               case "FilePurposeEnum":
                   return (FilePurposeEnum)whereInfo.ValueInt;
               case "FileStatusEnum":
                   return (FileStatusEnum)whereInfo.ValueInt;
               case "FileTypeEnum":
                   return (FileTypeEnum)whereInfo.ValueInt;
               case "InfrastructureTypeEnum":
                   return (InfrastructureTypeEnum)whereInfo.ValueInt;
               case "KMZActionEnum":
                   return (KMZActionEnum)whereInfo.ValueInt;
               case "LaboratoryEnum":
                   return (LaboratoryEnum)whereInfo.ValueInt;
               case "LabSheetStatusEnum":
                   return (LabSheetStatusEnum)whereInfo.ValueInt;
               case "LabSheetTypeEnum":
                   return (LabSheetTypeEnum)whereInfo.ValueInt;
               case "LanguageEnum":
                   return (LanguageEnum)whereInfo.ValueInt;
               case "LogCommandEnum":
                   return (LogCommandEnum)whereInfo.ValueInt;
               case "MapInfoDrawTypeEnum":
                   return (MapInfoDrawTypeEnum)whereInfo.ValueInt;
               case "MikeBoundaryConditionLevelOrVelocityEnum":
                   return (MikeBoundaryConditionLevelOrVelocityEnum)whereInfo.ValueInt;
               case "MikeScenarioSpecialResultKMLTypeEnum":
                   return (MikeScenarioSpecialResultKMLTypeEnum)whereInfo.ValueInt;
               case "MWQMSiteLatestClassificationEnum":
                   return (MWQMSiteLatestClassificationEnum)whereInfo.ValueInt;
               case "PolSourceInactiveReasonEnum":
                   return (PolSourceInactiveReasonEnum)whereInfo.ValueInt;
               case "PolSourceIssueRiskEnum":
                   return (PolSourceIssueRiskEnum)whereInfo.ValueInt;
               case "PositionEnum":
                   return (PositionEnum)whereInfo.ValueInt;
               case "PreliminaryTreatmentTypeEnum":
                   return (PreliminaryTreatmentTypeEnum)whereInfo.ValueInt;
               case "PrimaryTreatmentTypeEnum":
                   return (PrimaryTreatmentTypeEnum)whereInfo.ValueInt;
               case "PropertyTypeEnum":
                   return (PropertyTypeEnum)whereInfo.ValueInt;
               case "ReportConditionEnum":
                   return (ReportConditionEnum)whereInfo.ValueInt;
               case "ReportFieldTypeEnum":
                   return (ReportFieldTypeEnum)whereInfo.ValueInt;
               case "ReportFileTypeEnum":
                   return (ReportFileTypeEnum)whereInfo.ValueInt;
               case "ReportFormatingDateEnum":
                   return (ReportFormatingDateEnum)whereInfo.ValueInt;
               case "ReportFormatingNumberEnum":
                   return (ReportFormatingNumberEnum)whereInfo.ValueInt;
               case "ReportGenerateObjectsKeywordEnum":
                   return (ReportGenerateObjectsKeywordEnum)whereInfo.ValueInt;
               case "ReportSortingEnum":
                   return (ReportSortingEnum)whereInfo.ValueInt;
               case "ReportTreeNodeSubTypeEnum":
                   return (ReportTreeNodeSubTypeEnum)whereInfo.ValueInt;
               case "ReportTreeNodeTypeEnum":
                   return (ReportTreeNodeTypeEnum)whereInfo.ValueInt;
               case "SameDayNextDayEnum":
                   return (SameDayNextDayEnum)whereInfo.ValueInt;
               case "SampleMatrixEnum":
                   return (SampleMatrixEnum)whereInfo.ValueInt;
               case "SampleStatusEnum":
                   return (SampleStatusEnum)whereInfo.ValueInt;
               case "SampleTypeEnum":
                   return (SampleTypeEnum)whereInfo.ValueInt;
               case "SamplingPlanTypeEnum":
                   return (SamplingPlanTypeEnum)whereInfo.ValueInt;
               case "ScenarioStatusEnum":
                   return (ScenarioStatusEnum)whereInfo.ValueInt;
               case "SearchTagEnum":
                   return (SearchTagEnum)whereInfo.ValueInt;
               case "SecondaryTreatmentTypeEnum":
                   return (SecondaryTreatmentTypeEnum)whereInfo.ValueInt;
               case "SiteTypeEnum":
                   return (SiteTypeEnum)whereInfo.ValueInt;
               case "SpecialTableTypeEnum":
                   return (SpecialTableTypeEnum)whereInfo.ValueInt;
               case "StorageDataTypeEnum":
                   return (StorageDataTypeEnum)whereInfo.ValueInt;
               case "StreetTypeEnum":
                   return (StreetTypeEnum)whereInfo.ValueInt;
               case "TelTypeEnum":
                   return (TelTypeEnum)whereInfo.ValueInt;
               case "TertiaryTreatmentTypeEnum":
                   return (TertiaryTreatmentTypeEnum)whereInfo.ValueInt;
               case "TideDataTypeEnum":
                   return (TideDataTypeEnum)whereInfo.ValueInt;
               case "TideTextEnum":
                   return (TideTextEnum)whereInfo.ValueInt;
               case "TranslationStatusEnum":
                   return (TranslationStatusEnum)whereInfo.ValueInt;
               case "TreatmentTypeEnum":
                   return (TreatmentTypeEnum)whereInfo.ValueInt;
               case "TVAuthEnum":
                   return (TVAuthEnum)whereInfo.ValueInt;
               case "TVTypeEnum":
                   return (TVTypeEnum)whereInfo.ValueInt;
               case "ValveTypeEnum":
                   return (ValveTypeEnum)whereInfo.ValueInt;
               case "WebTideDataSetEnum":
                   return (WebTideDataSetEnum)whereInfo.ValueInt;
               case "WhereOperatorEnum":
                   return (WhereOperatorEnum)whereInfo.ValueInt;
               case "PolSourceObsInfoEnum":
                   return (PolSourceObsInfoEnum)whereInfo.ValueInt;
               default:
                   return null;
            }
        }
    }
}
