/*
 * Auto generated from C:\CSSPTools\src\codegen\AngularComponentsGenerated\bin\Debug\netcoreapp3.1\AngularComponentsGenerated.exe
 *
 * Do not edit this file.
 *
 */

import { HttpRequestModel } from '../../models/http.model';
import { TideLocation } from 'src/app/models/generated/TideLocation.model';

export interface TideLocationTextModel {
    Title?: string
}

export interface TideLocationModel extends HttpRequestModel {
    TideLocationList: TideLocation[];
}
