/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [\srcWithDoc\[ModelClassName]Generated.cs] button
 *
 * Do not edit this file.
 *
 */ 
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**No DB properties** :</para>
    /// > <para>**Other properties** : [Summary](CSSPModels.InputSummary.html#CSSPModels_InputSummary_Summary), [CSSPError.HasErrors](CSSPModels.CSSPError.html#CSSPModels_CSSPError_HasErrors), [CSSPError.ValidationResults](CSSPModels.CSSPError.html#CSSPModels_CSSPError_ValidationResults)</para>
    /// > 
    /// > <para>**Inherits [CSSPError](CSSPModels.CSSPError.html)**</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    [NotMapped]
    public partial class InputSummary : CSSPError
    {
        #region Properties in DB
        #endregion Properties in DB

        #region Properties not in DB
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPDisplayEN](CSSPModels.CSSPDisplayEN.html)(DisplayEN = "Summary")]</para>
        /// > <para>[[CSSPDisplayFR](CSSPModels.CSSPDisplayFR.html)(DisplayFR = "Sommaire")]</para>
        /// > <para>[[CSSPDescriptionEN](CSSPModels.CSSPDescriptionEN.html)(DescriptionEN = "Summary of the pollution sources for MIKE")]</para>
        /// > <para>[[CSSPDescriptionFR](CSSPModels.CSSPDescriptionFR.html)(DescriptionFR = "Sommaire des sources de pollution pour MIKE")]</para>
        /// </summary>
        /// <returns>
        /// 
        /// **Display (en)** --- Summary
        /// 
        /// **Display (fr)** --- Sommaire
        /// 
        /// **Description (en)** --- Summary of the pollution sources for MIKE
        /// 
        /// **Description (fr)** --- Sommaire des sources de pollution pour MIKE
        /// </returns>
        [CSSPDisplayEN(DisplayEN = "Summary")]
        [CSSPDisplayFR(DisplayFR = "Sommaire")]
        [CSSPDescriptionEN(DescriptionEN = @"Summary of the pollution sources for MIKE")]
        [CSSPDescriptionFR(DescriptionFR = @"Sommaire des sources de pollution pour MIKE")]
        public string Summary { get; set; }
        #endregion Properties not in DB

        #region Constructors
        public InputSummary() : base()
        {
        }
        #endregion Constructors
    }
}
