/*
 * Auto generated from the CSSPCodeWriter.proj by clicking on the [\srcWithDoc\[ModelClassName]Generated.cs] button
 *
 * Do not edit this file.
 *
 */ 
using CSSPEnums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace CSSPModels
{
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**DB properties for table MWQMSites** : [MWQMSiteID](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteID), [MWQMSiteTVItemID](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteTVItemID), [MWQMSiteNumber](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteNumber), [MWQMSiteDescription](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteDescription), [MWQMSiteLatestClassification](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteLatestClassification), [Ordinal](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_Ordinal), [LastUpdate.LastUpdateDate_UTC](CSSPModels.LastUpdate.html#CSSPModels_LastUpdate_LastUpdateDate_UTC), [LastUpdate.LastUpdateContactTVItemID](CSSPModels.LastUpdate.html#CSSPModels_LastUpdate_LastUpdateContactTVItemID)</para>
    /// > <para>**Other properties** : [CSSPError.HasErrors](CSSPModels.CSSPError.html#CSSPModels_CSSPError_HasErrors), [CSSPError.ValidationResults](CSSPModels.CSSPError.html#CSSPModels_CSSPError_ValidationResults)</para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [MWQMSiteService](CSSPServices.MWQMSiteService.html)</para>
    /// > <para>**Used by [CSSPWebAPI.Controllers](CSSPWebAPI.Controllers.html)** : [MWQMSiteController](CSSPWebAPI.Controllers.MWQMSiteController.html)</para>
    /// > <para>**Requires [CSSPEnums](CSSPEnums.html)** : [MWQMSiteLatestClassificationEnum](CSSPEnums.MWQMSiteLatestClassificationEnum.html)</para>
    /// > <para>**Inherits [LastUpdate](CSSPModels.LastUpdate.html)**</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
    public partial class MWQMSite : LastUpdate
    {
        #region Properties in DB
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPDisplayEN](CSSPModels.CSSPDisplayEN.html)(DisplayEN = "MWQMSite ID")]</para>
        /// > <para>[[CSSPDisplayFR](CSSPModels.CSSPDisplayFR.html)(DisplayFR = "MWQMSite ID")]</para>
        /// > <para>[[CSSPDescriptionEN](CSSPModels.CSSPDescriptionEN.html)(DescriptionEN = "Contains the unique "identifier on each row of the MWQMSites table")]</para>
        /// > <para>[[CSSPDescriptionFR](CSSPModels.CSSPDescriptionFR.html)(DescriptionFR = "Contient l'identifiant unique sur chaque ligne de la table MWQMSites")]</para>
        /// </summary>
        /// <returns>
        /// 
        /// **Display (en)** --- MWQMSite ID
        /// 
        /// **Display (fr)** --- MWQMSite ID
        /// 
        /// **Description (en)** --- Contains the unique "identifier on each row of the MWQMSites table
        /// 
        /// **Description (fr)** --- Contient l'identifiant unique sur chaque ligne de la table MWQMSites
        /// </returns>
        [Key]
        [CSSPDisplayEN(DisplayEN = "MWQMSite ID")]
        [CSSPDisplayFR(DisplayFR = "MWQMSite ID")]
        [CSSPDescriptionEN(DescriptionEN = @"Contains the unique ""identifier on each row of the MWQMSites table")]
        [CSSPDescriptionFR(DescriptionFR = @"Contient l'identifiant unique sur chaque ligne de la table MWQMSites")]
        public int MWQMSiteID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>**AllowableTVTypeList is of type [CSSPEnums.TVTypeEnum](CSSPEnums.TVTypeEnum.html)**</para>
        /// > <para>16 == MWQMSite</para>
        /// > <para>[[CSSPExist](CSSPModels.CSSPExistAttribute.html)(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVTypeList = "16")]</para>
        /// > <para>[[CSSPDisplayEN](CSSPModels.CSSPDisplayEN.html)(DisplayEN = "MWQM site TVItemID")]</para>
        /// > <para>[[CSSPDisplayFR](CSSPModels.CSSPDisplayFR.html)(DisplayFR = "Site MWQM TVItemID (fr)")]</para>
        /// > <para>[[CSSPDescriptionEN](CSSPModels.CSSPDescriptionEN.html)(DescriptionEN = "Link to the TVItems table representing MWQM site")]</para>
        /// > <para>[[CSSPDescriptionFR](CSSPModels.CSSPDescriptionFR.html)(DescriptionFR = "Lien à la table TVItems représentant le site MWQM (fr)")]</para>
        /// </summary>
        /// <returns>
        /// 
        /// **Display (en)** --- MWQM site TVItemID
        /// 
        /// **Display (fr)** --- Site MWQM TVItemID (fr)
        /// 
        /// **Description (en)** --- Link to the TVItems table representing MWQM site
        /// 
        /// **Description (fr)** --- Lien à la table TVItems représentant le site MWQM (fr)
        /// </returns>
        [CSSPExist(ExistTypeName = "TVItem", ExistPlurial = "s", ExistFieldID = "TVItemID", AllowableTVTypeList = "16")]
        [CSSPDisplayEN(DisplayEN = "MWQM site TVItemID")]
        [CSSPDisplayFR(DisplayFR = "Site MWQM TVItemID (fr)")]
        [CSSPDescriptionEN(DescriptionEN = @"Link to the TVItems table representing MWQM site")]
        [CSSPDescriptionFR(DescriptionFR = @"Lien à la table TVItems représentant le site MWQM (fr)")]
        public int MWQMSiteTVItemID { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPDisplayEN](CSSPModels.CSSPDisplayEN.html)(DisplayEN = "MWQM site number")]</para>
        /// > <para>[[CSSPDisplayFR](CSSPModels.CSSPDisplayFR.html)(DisplayFR = "Numéro du site MWQM (fr)")]</para>
        /// > <para>[[CSSPDescriptionEN](CSSPModels.CSSPDescriptionEN.html)(DescriptionEN = "MWQM site number")]</para>
        /// > <para>[[CSSPDescriptionFR](CSSPModels.CSSPDescriptionFR.html)(DescriptionFR = "Numéro du site MWQM (fr)")]</para>
        /// </summary>
        /// <returns>
        /// 
        /// **Display (en)** --- MWQM site number
        /// 
        /// **Display (fr)** --- Numéro du site MWQM (fr)
        /// 
        /// **Description (en)** --- MWQM site number
        /// 
        /// **Description (fr)** --- Numéro du site MWQM (fr)
        /// </returns>
        [StringLength(8)]
        [CSSPDisplayEN(DisplayEN = "MWQM site number")]
        [CSSPDisplayFR(DisplayFR = "Numéro du site MWQM (fr)")]
        [CSSPDescriptionEN(DescriptionEN = @"MWQM site number")]
        [CSSPDescriptionFR(DescriptionFR = @"Numéro du site MWQM (fr)")]
        public string MWQMSiteNumber { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPDisplayEN](CSSPModels.CSSPDisplayEN.html)(DisplayEN = "MWQM site description")]</para>
        /// > <para>[[CSSPDisplayFR](CSSPModels.CSSPDisplayFR.html)(DisplayFR = "Description du site MWQM (fr)")]</para>
        /// > <para>[[CSSPDescriptionEN](CSSPModels.CSSPDescriptionEN.html)(DescriptionEN = "MWQM site description")]</para>
        /// > <para>[[CSSPDescriptionFR](CSSPModels.CSSPDescriptionFR.html)(DescriptionFR = "Description du site MWQM (fr)")]</para>
        /// </summary>
        /// <returns>
        /// 
        /// **Display (en)** --- MWQM site description
        /// 
        /// **Display (fr)** --- Description du site MWQM (fr)
        /// 
        /// **Description (en)** --- MWQM site description
        /// 
        /// **Description (fr)** --- Description du site MWQM (fr)
        /// </returns>
        [StringLength(200)]
        [CSSPDisplayEN(DisplayEN = "MWQM site description")]
        [CSSPDisplayFR(DisplayFR = "Description du site MWQM (fr)")]
        [CSSPDescriptionEN(DescriptionEN = @"MWQM site description")]
        [CSSPDescriptionFR(DescriptionFR = @"Description du site MWQM (fr)")]
        public string MWQMSiteDescription { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPEnumType](CSSPModels.CSSPEnumTypeAttribute.html)]</para>
        /// > <para>[[CSSPDisplayEN](CSSPModels.CSSPDisplayEN.html)(DisplayEN = "MWQM site latest classification")]</para>
        /// > <para>[[CSSPDisplayFR](CSSPModels.CSSPDisplayFR.html)(DisplayFR = "Dernière classification du site MWQM (fr)")]</para>
        /// > <para>[[CSSPDescriptionEN](CSSPModels.CSSPDescriptionEN.html)(DescriptionEN = "MWQM site latest classification")]</para>
        /// > <para>[[CSSPDescriptionFR](CSSPModels.CSSPDescriptionFR.html)(DescriptionFR = "Dernière classification du site MWQM (fr)")]</para>
        /// </summary>
        /// <returns>
        /// 
        /// **Display (en)** --- MWQM site latest classification
        /// 
        /// **Display (fr)** --- Dernière classification du site MWQM (fr)
        /// 
        /// **Description (en)** --- MWQM site latest classification
        /// 
        /// **Description (fr)** --- Dernière classification du site MWQM (fr)
        /// </returns>
        [CSSPEnumType]
        [CSSPDisplayEN(DisplayEN = "MWQM site latest classification")]
        [CSSPDisplayFR(DisplayFR = "Dernière classification du site MWQM (fr)")]
        [CSSPDescriptionEN(DescriptionEN = @"MWQM site latest classification")]
        [CSSPDescriptionFR(DescriptionFR = @"Dernière classification du site MWQM (fr)")]
        public MWQMSiteLatestClassificationEnum MWQMSiteLatestClassification { get; set; }
        /// <summary>
        /// > [!NOTE]
        /// > <para>**Other custom attributes**</para>
        /// > <para>[[CSSPDisplayEN](CSSPModels.CSSPDisplayEN.html)(DisplayEN = "Ordinal")]</para>
        /// > <para>[[CSSPDisplayFR](CSSPModels.CSSPDisplayFR.html)(DisplayFR = "Ordre")]</para>
        /// > <para>[[CSSPDescriptionEN](CSSPModels.CSSPDescriptionEN.html)(DescriptionEN = "Ordinal")]</para>
        /// > <para>[[CSSPDescriptionFR](CSSPModels.CSSPDescriptionFR.html)(DescriptionFR = "Ordre")]</para>
        /// </summary>
        /// <returns>
        /// 
        /// **Display (en)** --- Ordinal
        /// 
        /// **Display (fr)** --- Ordre
        /// 
        /// **Description (en)** --- Ordinal
        /// 
        /// **Description (fr)** --- Ordre
        /// </returns>
        [Range(0, 1000)]
        [CSSPDisplayEN(DisplayEN = "Ordinal")]
        [CSSPDisplayFR(DisplayFR = "Ordre")]
        [CSSPDescriptionEN(DescriptionEN = @"Ordinal")]
        [CSSPDescriptionFR(DescriptionFR = @"Ordre")]
        public int Ordinal { get; set; }
        #endregion Properties in DB

        #region Constructors
        public MWQMSite() : base()
        {
        }
        #endregion Constructors
    }
    /// <summary>
    /// > [!NOTE]
    /// > 
    /// > <para>**No DB properties** :</para>
    /// > <para>**Other properties** : [MWQMSiteID](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteID), [MWQMSiteTVItemID](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteTVItemID), [MWQMSiteNumber](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteNumber), [MWQMSiteDescription](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteDescription), [MWQMSiteLatestClassification](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_MWQMSiteLatestClassification), [Ordinal](CSSPModels.MWQMSite.html#CSSPModels_MWQMSite_Ordinal)</para>
    /// > 
    /// > <para>**Used by [CSSPServices](CSSPServices.html)** : [MWQMSiteService](CSSPServices.MWQMSiteService.html)</para>
    /// > <para>**Used by [CSSPWebAPI.Controllers](CSSPWebAPI.Controllers.html)** : [MWQMSiteController](CSSPWebAPI.Controllers.MWQMSiteController.html)</para>
    /// > <para>**Requires [CSSPEnums](CSSPEnums.html)** : [MWQMSiteLatestClassificationEnum](CSSPEnums.MWQMSiteLatestClassificationEnum.html)</para>
    /// > <para>**Return to [CSSPModels](CSSPModels.html)**</para>
    /// </summary>
}
